#!/bin/bash
#
#    bl-user-setup: a script to populate a new user's HOME directory
#    using template files from /usr/share/bunsen/skel/
#    Copyright: 2015-2016 John Crawley <john@bunsenlabs.org>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

declare USER=${USER} # environment set by lightdm
declare USERHOME

# LDAP/ActiveDirectory users are known as user@domain. Retrieve just the
# user.
if [[ $USER =~ @ ]]; then
    USER=${USER%%@*}
fi

if [[ "$USER" = root ]]; then 
    echo "$0: ERROR: USER is root, abort" >&2
    exit 1
fi

# Check for the user home directory
USERHOME=$(getent passwd "$USER" | cut -d: -f6)
if [[ -z "$USERHOME" || ! -d "$USERHOME" ]]; then
    echo "$0: ERROR: user home directory <$USERHOME> is not set or does not exist." >&2
    exit 1
fi

# Setup already ran, do nothing.
[[ -f "$USERHOME/.config/bunsen/bl-setup" ]] && exit 0

bkp_sfx="~$( date +%FT%T )~"

rsync -rltb --suffix="$bkp_sfx" --safe-links /usr/share/bunsen/skel/ "$USERHOME"

for i in "$USERHOME/.gtk-bookmarks" "$USERHOME/.config/nitrogen/nitrogen.cfg"
do
    [[ -f "${i}.template" ]] || continue
    sed --in-place "s/%USERNAME%/$USER/g" "${i}.template"
    if [[ -f "$i" ]]
    then
        if diff -BEbZ "$i" "${i}.template" >/dev/null
        then
            rm "${i}.template"
        else
            mv "$i" "${i}${bkp_sfx}"
            mv "${i}.template" "$i"
        fi
    else
        mv "${i}.template" "$i"
    fi
done

ln -sTf /usr/share/images/bunsen/wallpapers "$USERHOME/Pictures/wallpapers/bunsen"

mkdir -p "/home/$USER/.config/bunsen" # this should already exist
touch "$USERHOME/.config/bunsen/bl-setup"

chown -R "$USER":"$USER" "$USERHOME"

exit 0
